config/routes.rb
ImageWorld::Application.routes.draw do
  root :to => "home_page#index"
  resources :home_page
  resources :categories
  resources :works
  resources :projects
  resources :images
  resources :users
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :skip => [:registrations]
  devise_scope :users do
  end
end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :category
	belongs_to :project
	has_many :images, :dependent => :destroy
	attr_accessible :category_id, :project_id, :name, :description, :images_attributes
	accepts_nested_attributes_for :images

	validates :name, presence: true
	validates :category_id, presence: true
	#validates :project_id, presence: true

	validates_uniqueness_of :name, :scope => [:category_id, :project_id]

	def next_image_version
		version = 0
        if images.count == 0
          version = 1
        else
          version = images.order("version ASC").last.version + 1
        end
        version
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @table_id = "works"
    @works = Work.page(params[:page]).order("id ASC")
    respond_to do |format|
      format.html
      format.json { render json: @works }
    end
  end

  def show
    @work = nil
    if params[:project_id]
      @work = Project.find(params[:project_id]).general_work
    else
      @work = Work.find(params[:id])
    end
    session[:work_id] = params[:id]
    session[:work_action] = "show"
    @images = @work.images.order("version DESC")
    respond_to do |format|
      format.html
      format.json { render json: @work }
    end
  end

  def new
    @work = Work.new
    respond_to do |format|
      format.html
      format.json { render json: @work }
    end
  end

  def edit
    @work = Work.find(params[:id])
    session[:work_id] = params[:id]
    session[:work_action] = "edit"
    @images = @work.images.order("version DESC")
    respond_to do |format|
      format.html
      format.json { render json: @work }
    end
  end

  def create
    @work = Work.new(params[:work])
    respond_to do |format|
      if @work.save
        format.html { redirect_to @work }
        format.json { render json: @work, status: :created }
      else
        puts "error on creating Work"
        puts @work.errors.count
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @work = Work.find(params[:id])
    respond_to do |format|
      if @work.update_attributes(params[:work])
        if params[:work] and params[:work][:images_attributes]
          version = 0
          if @work.images.last.version.nil?
            if @work.images.count == 1
              version = 1
            else
              version = @work.images.order("version ASC").last.version + 1
            end
            @work.images.last.update_attributes(:version => version)
          end
        end
        format.html { redirect_to @work }
        format.json { head :no_content }
      else
        puts "error on updating Work"
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work = Work.find(params[:id])
    if @work.destroy
      respond_to do |format|
        format.html { redirect_to works_path}
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        puts "error on destroying Work"
        format.html { redirect_to Work_path, alert: @work.errors.full_messages.to_sentence }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<% if @work.errors.any? or flash[:error] %>
  <div class="alert-message error">
    <p>
      <strong>
          <% if @work.errors.any? %>
            <%= t "errors.save_error", :count => @work.errors.count, :save_obj => (t "work") %>
            <br />
            <% @work.errors.full_messages.each do |msg| %>
                <strong>- <%= msg %></strong><br/>
            <% end %>
          <% elsif flash[:error] %>
            <%= (t "errors.save_error") %> <%= flash[:error] %>
          <% end %>
      </strong>
    </p>
  </div>
<% end %>

<%= simple_form_for @work do |f| %>
  <div class="image_world inner_wrap">
    <div class="image_world form fields">
      <% if (@work.new_record?) || (@work.category.id != 1) %>
        <div class="image_world form field">
          <%= f.input :category_id, :label=> (t "model.category.singular"), :label_html => {:class => "image_world form field label"}, :collection => Category.where("id != 1").collect{|r| [r.name, r.id]}, :as => :select %>
        </div>
        <div class="image_world form field odd"> 
          <%= f.input :project_id, :label=> (t "model.project.singular"), :label_html => {:class => "image_world form field label"}, :collection => Project.all.collect{|r| [r.name, r.id]}, :as => :select %>
        </div>
      <% end %>
      <div class="image_world form field">
        <%= f.input :name, :label => (t "attributes.name"), :label_html => {:class => "image_world form field label"} %> 
      </div>
      <div class="image_world form field odd">
        <%= f.input :description, :label => (t "attributes.description"), :label_html => {:class => "image_world form field label"} %> 
      </div>
      <div class="image_world container form submit"><%= f.button :submit, :id=> "fs", :value=>(t "actions.save") %></div>
    </div>
  </div>
<% end %>

app/views/works/_image.html.erb
<tr>
    <td><%= image.id %></td>
    <td><%= link_to image_tag(image.image_file_url(:thumb).to_s, size: "55x55"), image_path(image) %></td>
    <td>
        <% if image.work.project %>
          <%= link_to image.work.project.name, project_path(image.work.project) %>
        <% else %>
          <%= (t "other") %>
        <% end %>
    </td>
    <td><%= link_to image.work.category.name, category_path(image.work.category) %></td>
    <td><%= link_to image.work.name, work_path(image.work) %></td>
    <td><%= link_to image.version, image_path(image) %></td>
    <td><%= image.note %></td>
    <td><%= image.created_at %></td>
    <td><%= image.updated_at %></td>
    <td>
        <%= link_to (t "actions.show"), image_path(image) %>
         | 
        <%= link_to (t "actions.edit"), edit_image_path(image) %>
    </td>
</tr>

app/views/works/_images.html.erb
<% if work.images.count > 0 %>
  <table border="1" class="image_world work images">
	<tr>
	  <td><%= (t "attributes.id") %></td>
	  <td><%= (t "attributes.image") %></td>
	  <td><%= (t "model.project.singular") %></td>
	  <td><%= (t "model.category.singular") %></td>
	  <td><%= (t "model.work.singular") %></td>
	  <td><%= (t "attributes.version") %></td>
	  <td><%= (t "attributes.note") %></td>
	  <td><%= (t "attributes.created_at") %></td>
	  <td><%= (t "attributes.updated_at") %></td>
	  <td><%= (t "attributes.general_actions") %></td>
	</tr>
    <% work.images.reverse.each do |image| %>
	  <div class="image_world container work image">
	    <%= render :partial => "image", :locals => {:image => image} %>
	  </div>
    <% end %>
  </table>
<% else %>
  <div class="image_world text not_exist"><%= (t "model.image.not_exist").upcase %></div>
<% end %>

app/views/works/_new_image.html.erb
<div class="image_world container project category new_work"><%= (t "model.image.new") %></div>
<%= simple_form_for work do |f| %>
  <div class="image_world inner_wrap">
    <div class="image_world form fields without_margin">
      <%= f.simple_fields_for :images, work.images.build do |image| %>
      	<div class="image_world form field">
  	      <%= image.hidden_field :version, :value => work.next_image_version %>
  	    </div>
  	    <div class="image_world form field odd">
          <%= image.input :image_file, :label=> (t "attributes.image_file"), :label_html => {:class => "image_world form field label"}, :as => :file %>
        </div>
        <div class="image_world form field">
          <%= image.input :note, :label=> (t "attributes.note"), :label_html => {:class => "image_world form field label"} %>
        </div>
      <% end %>
      <div class="image_world container form submit"><%= f.button :submit, :id=> "fs", :value=>(t "actions.save") %></div>
	</div>
  </div>
<% end %>

app/views/works/_page_title.html.erb
<div class="image_world text item_name">
  <%= work.name %>
</div>
<div class="image_world text item_seperator"> | </div>
<div class="image_world text item_description">
  <%= work.description %>
</div>

app/views/works/_path.html.erb
<% if work.project %>
  <div class="image_world path element link first">
    <%= link_to work.project.name, project_path(work.project) %>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= link_to work.category.name, category_path(work.category) %>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link third">
    <%= link_to work.name, work_path(work) %>
  </div>
<% else %>
  <div class="image_world path element link first">
    <%= link_to work.category.name, category_path(work.category) %>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= link_to work.name, work_path(work) %>
  </div>
<% end %>

app/views/works/_work.html.erb
<tr>
    <td><%= work.id %></td>
    <td><%= link_to work.category.name, category_path(work.category) %></td>
    <% if work.project %>
        <td><%= link_to work.project.name, project_path(work.project) %></td>
    <% else %>    
        <td><%= (t "other") %></td>
    <% end %>
    <td><%= link_to work.name, work_path(work) %></td>
    <td><%= work.description %></td>
    <td class="act">
        <%= link_to (t "actions.show"), work_path(work) %>
        <% if work.category.id != 1 %>
            <%= link_to (t "actions.edit"), edit_work_path(work) %>
            <%= link_to (t "actions.destroy"), work_path(work), confirm: (t "actions.confirm"), method: :delete %>
        <% end %>
    </td>
</tr>

app/views/works/edit.html.erb
<%= content_for :path do %>
  <%= render :partial => "path", :locals => {:work => @work} %>
<% end %>

<%= content_for :general_actions do %>
  <% if @work.category.id != 1 %>
    <%= link_to (t "actions.show"), work_path(@work), :class => "image_world general_action link two" %>
    <%= link_to (t "actions.destroy"), work_path(@work), confirm: (t "actions.confirm"), method: :delete, :class => "image_world general_action link odd two" %>
  <% else %>
    <%= link_to (t "actions.show"), work_path(@work), :class => "image_world general_action link one" %>
  <% end %>
<% end %>

<%= content_for :page_title do %>
  <%= render :partial => "page_title", :locals => {:work => @work} %>
<% end %>

<%= render "form" %>

app/views/works/index.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.work.plural")%>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <%= link_to (t "actions.new"), new_work_path, :class => "image_world general_action link one" %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= (t "model.work.plural")%>
  </div>
<% end %>

<%= paginated_collection_content(@works, @table_id, [(t "attributes.id"), (t "model.category.singular"), (t "model.project.singular"), (t "attributes.name"), (t "attributes.description"), (t "attributes.general_actions")]) %>
<%= paginate_footer(@works) %>

app/views/works/new.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.work.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= (t "actions.new") %>
  </div>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= (t "model.work.new") %>
  </div>
<% end %>

<%= render "form" %>

<script>
  $("#left_new_work").addClass("selected");
</script>

app/views/works/show.html.erb
<%= content_for :path do %>
  <%= render :partial => "path", :locals => {:work => @work} %>
<% end %>

<%= content_for :general_actions do %>
  <% if @work.category.id != 1 %>
    <%= link_to (t "actions.edit"), edit_work_path(@work), :class => "image_world general_action link two" %>
    <%= link_to (t "actions.destroy"), work_path(@work), confirm: (t "actions.confirm"), method: :delete, :class => "image_world general_action link odd two" %>
  <% else %>
    <%= link_to (t "actions.edit"), edit_work_path(@work), :class => "image_world general_action link one" %>
  <% end %>
<% end %>

<%= content_for :page_title do %>
  <%= render :partial => "page_title", :locals => {:work => @work} %>
<% end %>

<div class="image_world container category projects" scrolling="auto">
  <%= render :partial => "images", :locals => {:work => @work} %>
</div>

<div class="image_world container category new_work">
  <%= render :partial => "new_image", :locals => {:work => @work} %>
</div>