config/routes.rb
ImageWorld::Application.routes.draw do
  root :to => "home_page#index"
  resources :home_page
  resources :categories
  resources :works
  resources :projects
  resources :images
  resources :users
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :skip => [:registrations]
  devise_scope :users do
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :works, :dependent => :destroy
	has_many :images, :through => :works, :dependent => :destroy
	attr_accessible :name, :description, :works_attributes, :images_attributes
	accepts_nested_attributes_for :works, :images

	validates :name, presence: true, uniqueness: true

	def grouped_works
		other_works.group_by { |d| d[:category_id] }
	end

	def general_work
		works.first
	end

	def other_works
		array = Array.new(works)
		array.shift()
		array
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @table_id = "projects"
    @projects = Project.page(params[:page]).order("id ASC")
    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def new
    @project = Project.new
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def create
    @project = Project.new(params[:project])
    respond_to do |format|
      if @project.save
        @general_work = Work.new(:project_id => @project.id, :category_id => 1, :name => "General")
        @general_work.save
        format.html { redirect_to root_path }
        format.json { render json: @project, status: :created }
      else
        puts "error on creating Project"
        puts @project.errors.count
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project }
        format.json { head :no_content }
      else
        puts "error on updating Project"
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_path}
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        puts "error on destroying Project"
        format.html { redirect_to project_path, alert: @project.errors.full_messages.to_sentence }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if @project.errors.any? or flash[:error] %>
  <div class="alert-message error">
    <p>
      <strong>
          <% if @project.errors.any? %>
            <%= t "errors.save_error", :count => @project.errors.count, :save_obj => (t "project") %>
            <br />
            <% @project.errors.full_messages.each do |msg| %>
                <strong>- <%= msg %></strong><br/>
            <% end %>
          <% elsif flash[:error] %>
            <%= (t "errors.save_error") %> <%= flash[:error] %>
          <% end %>
      </strong>
    </p>
  </div>
<% end %>

<%= simple_form_for @project do |f| %>
  <div class="image_world inner_wrap">
    <div class="image_world form fields">
      <div class="image_world form field">
        <%= f.input :name, :label => (t "attributes.name"), :label_html => {:class => "image_world form field label"} %> 
      </div>
      <div class="image_world form field odd">
        <%= f.input :description, :label => (t "attributes.description"), :label_html => {:class => "image_world form field label"} %>
      </div>
      <div class="image_world container form submit"><%= f.button :submit, :id=> "fs", :value=>(t "actions.save") %></div>
    </div>
  </div>
<% end %>

app/views/projects/_list.html.erb
<div class="image_world text left_title" id="project_title">
	<%= link_to (t "model.project.plural"), projects_path, :class => "image_world left_link" %>
</div>
<div class="image_world container left project" id="left_project_container">
	<% if projects.count > 0 %>
		<% projects.each do |project| %>
			<div class="image_world left_item project" id="left_item_p<%= project.id %>">
				<%= link_to project.name, project_path(project), :onclick => "leftItemSelected(event)", :class => "image_world left_link", :id => "left_project_#{project.id}" %>
			</div>
		<% end %>
	<% else %>
		<div class="image_world text mini not_exist"><%= (t "model.project.not_exist").upcase %></div>
	<% end %>
</div>
<%= link_to (t "actions.new_project"), new_project_path, :class => "image_world left_item new", :id => "new_project" %>

app/views/projects/_new_work.html.erb
<div class="image_world container project category new_work"><%= (t "model.work.new") %></div>
<%= simple_form_for project do |f| %>
  <div class="image_world inner_wrap">
    <div class="image_world form fields without_margin">
	  <%= f.simple_fields_for :works, project.works.build do |work| %>
	    <div class="image_world form field">
	      <%= work.input :category_id, :label=> (t "model.category.singular"), :label_html => {:class => "image_world form field label"}, :collection => Category.all.collect{|r| [r.name, r.id]}, :as => :select %>
		</div>
		<div class="image_world form field odd">
		  <%= work.input :name, :label => (t "attributes.name"), :label_html => {:class => "image_world form field label"} %> 
		</div>
		<div class="image_world form field">
		  <%= work.input :description, :label => (t "attributes.description"), :label_html => {:class => "image_world form field label"} %> 
		</div>
	  <% end %>
      <div class="image_world container form submit"><%= f.button :submit, :id=> "fs", :value=>(t "actions.save") %></div>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
    <td><%= project.id %></td>
    <td><%= link_to project.name, project_path(project) %></td>
    <td><%= project.description %></td>
    <td class="act">
        <%= link_to (t "actions.show"), project_path(project) %>
        <%= link_to (t "actions.edit"), edit_project_path(project) %>
        <%= link_to (t "actions.destroy"), project_path(project), confirm: (t "actions.confirm"), method: :delete %>
    </td>
</tr>

app/views/projects/edit.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.project.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= link_to @project.name, project_path(@project) %>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <%= link_to (t "actions.show"), project_path(@project), :class => "image_world general_action link two" %>
  <%= link_to (t "actions.destroy"), project_path(@project), confirm: (t "actions.confirm"), method: :delete, :class => "image_world general_action link odd two" %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= @project.name %>
  </div>
  <div class="image_world text item_seperator"> | </div>
  <div class="image_world text item_description">
    <%= @project.description %>
  </div>
<% end %>

<%= render "form" %>

app/views/projects/index.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.project.plural")%>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <%= link_to (t "actions.new"), new_project_path, :class => "image_world general_action link one" %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= (t "model.project.plural")%>
  </div>
<% end %>

<% if @projects.count > 0 %>
  <%= paginated_collection_content(@projects, @table_id, [(t "attributes.id"), (t "attributes.name"), (t "attributes.description"), (t "attributes.general_actions")]) %>
  <%= paginate_footer(@projects) %>
<% else %>
  <div class="image_world text not_exist"><%= (t "model.project.not_exist").upcase %></div>
<% end %>

<script>
  $("#project_title").addClass("selected");
</script>

app/views/projects/new.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.project.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= (t "actions.new") %>
  </div>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= (t "model.project.new") %>
  </div>
<% end %>

<%= render "form" %>

<script>
  $("#new_project").addClass("selected");
</script>

app/views/projects/show.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.project.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= link_to @project.name, project_path(@project) %>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <%= link_to (t "actions.edit"), edit_project_path(@project), :class => "image_world general_action link two" %>
  <%= link_to (t "actions.destroy"), project_path(@project), confirm: (t "actions.confirm"), method: :delete, :class => "image_world general_action link odd two" %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= @project.name %>
  </div>
  <div class="image_world text item_seperator"> | </div>
  <div class="image_world text item_description">
    <%= @project.description %>
  </div>
<% end %>

<div class="image_world container category projects">
  <%= render :partial => "projects/category/list", :locals => {:project => @project} %>
</div>

<% if Category.all.count > 1 %>
  <div class="image_world container category new_work">
    <%= render :partial => "new_work", :locals => {:project => @project} %>
  </div>
<% end %>

<button type="button" id="hidden_project_button" style="display:none;" onclick="highlightProject('<%= @project.id %>')" ></button>

<script>
  $("#hidden_project_button").click();
function highlightProject(src) {
  $("#left_item_p" + src).addClass("selected");
}

</script>