config/routes.rb
ImageWorld::Application.routes.draw do
  root :to => "home_page#index"
  resources :home_page
  resources :categories
  resources :works
  resources :projects
  resources :images
  resources :users
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :skip => [:registrations]
  devise_scope :users do
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :works, :dependent => :destroy
	has_many :images, :through => :works, :dependent => :destroy
	attr_accessible :name, :description, :works_attributes, :images_attributes
	accepts_nested_attributes_for :works, :images

	validates :name, presence: true, uniqueness: true

	def grouped_works
		works.group_by { |d| d[:project_id] }
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @table_id = "categories"
    @categories = Category.page(params[:page]).order("id ASC")
    respond_to do |format|
      format.html
      format.json { render json: @categories }
    end
  end

  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def create
    @category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path }
        format.json { render json: @category, status: :created }
      else
        puts "error on creating Category"
        puts @category.errors.count
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category }
        format.json { head :no_content }
      else
        puts "error on updating Category"
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_path}
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        puts "error on destroying Category"
        format.html { redirect_to category_path, alert: @category.errors.full_messages.to_sentence }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
    <td><%= category.id %></td>
    <td><%= link_to category.name, category_path(category) %></td>
    <td><%= category.description %></td>
    <td class="act">
        <%= link_to (t "actions.show"), category_path(category) %>
        <%= link_to (t "actions.edit"), edit_category_path(category) %>
        <% if category.id != 1 %>
        	<%= link_to (t "actions.destroy"), category_path(category), confirm: (t "actions.confirm"), method: :delete %>
        <% end %>
    </td>
</tr>

app/views/categories/_form.html.erb
<% if @category.errors.any? or flash[:error] %>
  <div class="alert-message error">
    <p>
      <strong>
          <% if @category.errors.any? %>
            <%= t "errors.save_error", :count => @category.errors.count, :save_obj => (t "category") %>
            <br />
            <% @category.errors.full_messages.each do |msg| %>
                <strong>- <%= msg %></strong><br/>
            <% end %>
          <% elsif flash[:error] %>
            <%= (t "errors.save_error") %> <%= flash[:error] %>
          <% end %>
      </strong>
    </p>
  </div>
<% end %>

<%= simple_form_for @category do |f| %>
  <div class="image_world inner_wrap">
    <div class="image_world form fields">
      <div class="image_world form field">
        <%= f.input :name, :label => (t "attributes.name"), :label_html => {:class => "image_world form field label"} %> 
      </div>
      <div class="image_world form field odd">
        <%= f.input :description, :label => (t "attributes.description"), :label_html => {:class => "image_world form field label"} %>
      </div>
      <div class="image_world container form submit"><%= f.button :submit, :id=> "fs", :value=>(t "actions.save") %></div>
    </div>
  </div>
<% end %>

app/views/categories/_list.html.erb
<div class="image_world text left_title" id="category_title">
	<%= link_to (t "model.category.plural"), categories_path, :class => "image_world left_link" %>
</div>
<div class="image_world container left category" id="left_category_container">
	<% if categories.count > 0 %>
		<% categories.each do |category| %>
			<div class="image_world left_item category" id="left_item_c<%= category.id %>">
				<%= link_to category.name, category_path(category), :onclick => "leftItemSelected(event)", :class => "image_world left_link", :id => "left_category_#{category.id}" %>
			</div>
		<% end %>
	<% else %>
		<div class="image_world text not_exist"><%= (t "model.work.not_exist").upcase %></div>
	<% end %>
</div>
<%= link_to (t "actions.new_category"), new_category_path, :class => "image_world left_item new", :id => "new_category" %>

app/views/categories/_new_work.html.erb
<div class="image_world container project category new_work"><%= (t "model.work.new") %></div>
<%= simple_form_for category do |f| %>
  <div class="image_world inner_wrap">
    <div class="image_world form fields without_margin">
	  <%= f.simple_fields_for :works, category.works.build do |work| %>
	    <div class="image_world form field">
	      <%= work.input :project_id, :label=> (t "model.project.singular"), :label_html => {:class => "image_world form field label"}, :collection => Project.all.collect{|r| [r.name, r.id]}, :as => :select %>
		</div>
		<div class="image_world form field odd">
		  <%= work.input :name, :label => (t "attributes.name"), :label_html => {:class => "image_world form field label"} %>
		</div>
		<div class="image_world form field">
		  <%= work.input :description, :label => (t "attributes.description"), :label_html => {:class => "image_world form field label"} %>
		</div>
	  <% end %>
      <div class="image_world container form submit"><%= f.button :submit, :id=> "fs", :value=>(t "actions.save") %></div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.category.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= link_to @category.name, category_path(@category) %>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <% if @category.id != 1 %>
    <%= link_to (t "actions.show"), category_path(@category), :class => "image_world general_action link two" %>
    <%= link_to (t "actions.destroy"), category_path(@category), confirm: (t "actions.confirm"), method: :delete, :class => "image_world general_action link odd two" %>
  <% else %>
    <%= link_to (t "actions.show"), category_path(@category), :class => "image_world general_action link one" %>
  <% end %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= @category.name %>
  </div>
  <div class="image_world text item_seperator"> | </div>
  <div class="image_world text item_description">
    <%= @category.description %>
  </div>
<% end %>

<%= render "form" %>

app/views/categories/index.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.category.plural")%>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <%= link_to (t "actions.new"), new_category_path, :class => "image_world general_action link one" %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= (t "model.category.plural")%>
  </div>
<% end %>

<%= paginated_collection_content(@categories, @table_id, [(t "attributes.id"), (t "attributes.name"), (t "attributes.description"), (t "attributes.general_actions")]) %>
<%= paginate_footer(@categories) %>

<script>
  $("#category_title").addClass("selected");
</script>

app/views/categories/new.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.category.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= (t "actions.new") %>
  </div>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= (t "model.category.new") %>
  </div>
<% end %>

<%= render "form" %>

<script>
  $("#new_category").addClass("selected");
</script>

app/views/categories/show.html.erb
<%= content_for :path do %>
  <div class="image_world path element link first">
    <%= (t "model.category.singular")%>
  </div>
  <div class="image_world path element text seperator"> > </div>
  <div class="image_world path element link second">
    <%= link_to @category.name, category_path(@category) %>
  </div>
<% end %>

<%= content_for :general_actions do %>
  <% if @category.id != 1 %>
    <%= link_to (t "actions.edit"), edit_category_path(@category), :class => "image_world general_action link two" %>
    <%= link_to (t "actions.destroy"), category_path(@category), confirm: (t "actions.confirm"), method: :delete, :class => "image_world general_action link odd two" %>
  <% else %>
    <%= link_to (t "actions.edit"), edit_category_path(@category), :class => "image_world general_action link one" %>
  <% end %>
<% end %>

<%= content_for :page_title do %>
  <div class="image_world text item_name">
    <%= @category.name %>
  </div>
  <div class="image_world text item_seperator"> | </div>
  <div class="image_world text item_description">
    <%= @category.description %>
  </div>
<% end %>

<% if @category.id != 1 %>
  <div class="image_world container category projects">
<% else %>
  <div class="image_world container category projects general_category">
<% end %>
  <%= render :partial => "categories/project/list", :locals => {:category => @category} %>
</div>

<div class="image_world container category new_work">
  <% if @category.id != 1%>
    <%= render :partial => "new_work", :locals => {:category => @category} %>
  <% end %>
</div>

<button type="button" id="hidden_category_button" style="display:none;" onclick="highlightCategory('<%= @category.id %>')" ></button>

<script>
  $("#hidden_category_button").click();
function highlightCategory(src) {
  $("#left_item_c" + src).addClass("selected");
}

</script>